### PR TITLE
Fix migration warnings in scio-core

### PR DESCRIPTION
**Pull request by MaximeKjaer**
It seems like it's necessary to not be in migration mode in order to use the new Scala 3 `given` keyword. In order to be able to use this, I've fixed the migration warnings in `scio-core`, and have removed the migration mode.

I used the `-rewrite` option to help me fix some warnings. For the do-while, I preferred to rewrite it using a `var` rather than the [recommended style](https://dotty.epfl.ch/docs/reference/dropped-features/do-while.html), which I somewhat illegible...

### CODE REVIEW

**Comment by MaximeKjaer** [comment]
Oh no... Seems like some dependencies are using bintray, which is shutting down. Seems like dependencies have been somewhat updated on `upstream / main`, so we may need to do a rebase to fix this. I'll take care of it.

**Review by vincenzobaz — APPROVED** [review]
Are the `private[scio]` specific enough? For example could you replace with a subpackage such as `private[coders]` or `private[schema]`?

As long as it is in scio, we should be good to go. However using a more specific limiter is closer to the original `private`

**Comment by MaximeKjaer** [comment]
Thank you, this is a good point. Where possible, I've made the private scope of constructors more specific.

**Comment by MaximeKjaer** [comment]
If tests pass, I suggest we squash and merge.

**Pull request merged**
